config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  devise_for :users

  resources :users
   
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :articles 
     resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
	  validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 } 
    has_rich_text :body
    has_one_attached :image
    validate :acceptable_image

   def acceptable_image
     return unless image.attached? 
   end
   
end

app/models/comment.rb
class Comment < ApplicationRecord
   belongs_to :user
end

app/models/like.rb
class Like

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
     @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @comments=Comment.all
  end

  def new
    @article = Article.new
  end

   def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
     @article = Article.find(params[:id])
     @article.destroy
     
     redirect_to root_path, status: :see_other 
  end

  private

    def article_params
      params.require(:article).permit(:title, :body, :image)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def show
     @comment = Comment.find(params[:id])
  end
  def new
   @comment = Comment.new
  end
  def create 
    @comment = Comment.new(comment_params)
    if @comment.save
       redirect_to @comment
   end
 end
  def destroy
     
    @comment = Comment.find(params[:id])
    @comment.destroy
         redirect_to
     
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.rich_text_area:body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
     <%= form.file_field :image%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles </h1>
<table class="table table-striped">
<thead class="thead-dark">	
<tr>
	<th>ID</th>
	<th>Title</th>
	<th>Body</th>
<tr>
</thead>
<tbody>
<tr>
<% @articles.each do |article| %>
    <td><%= article.id %></td>
    <td><%= article.title %></td>
    <td><%= article.body %></td> 
    <td><%= link_to 'show', article_path(article), class:"btn btn-info"%></td>
    <td><%= link_to "Edit", edit_article_path(article), class:"btn btn-secondary"%></td>
   
   <td> <%= link_to "Destroy", article_path(article), data: { turbo_method: :delete,turbo_confirm: "Are you sure?"},class:"btn btn-danger" %></td>
</tr>   
	<%end%>
</tbody>
</table>



<br>
<br>
<%= link_to "New Article", new_article_path, class:"btn btn-primary"%>

app/views/articles/new.html.erb
 <h1>New Article</h1>

<%= form_with model: @article do |form| %>
 
  <div class="field form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title , class:"form-control" %>
    <% @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
   
   <div class="field">
     <%= form.file_field :image%>
   </div>
  <div class="field form-group">
    <%= form.label :body %><br>
    <%= form.rich_text_area :body, class:"form-control"%><br>
    <% @article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="field form-group">
    <%= form.submit class:"btn btn-success"%>
  </div>
<% end %>

app/views/articles/show.html.erb
<div class="container-fluid">
 <p>
  <strong style="color:#58D68D">Title:</strong>
  <%= @article.title %>
 </p>
 
 <p>
  <strong style="color:#58D68D">Body:</strong>
  <%= @article.body %>
 </p>

<div>
   <p>
    <%= image_tag(article.image, style:"width:50%")%>
 </p>

<ul>
    <%= link_to "edit", edit_article_path(@article), class: "btn btn-secondary" %> 
    <%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }, class:"btn btn-danger" %>
      
</ul>


<br>
<br/>

<%= render "comments/comment" , comment:@comments%>

 <%= link_to "comment" ,new_comment_path(@article), class:"btn btn-info"%>
 

app/views/comments/_comment.html.erb
<% @comments.each do |comment|%>
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<p>
   <i><%= comment.user.email%></i>
<p>
  <%= link_to "Destroy Comment",comment_path(comment), data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              }, class:"btn btn-primary" %>
</p>
<% end %>

 

app/views/comments/_form.html.erb
<h2>Add a comment:</h2>
<%= form_with model: comment do |form| %>
  <div class:" field form-group">
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter, class:"form-control" %>
  </p>
  <div class:" field form-group">
    <%= form.label :body %><br>
    <%= form.text_area :body, class:"form-control" %>
  </div>
  <div class:" field form-group">
    <%= form.label :user_Id %><br>
    <%= form.text_field :user_id, class:"form-control" ,value: current_user.id %>
  </div>
  <div class="field form-group">
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %> 

app/views/comments/new.html.erb
<h2>Add a comment:</h2>
<%= form_with model: @comment do |form| %>
  <div class:" field form-group">
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter, class:"form-control" %>
  </p>
  <div class:" field form-group">
    <%= form.label :body %><br>
    <%= form.text_area :body, class:"form-control" %>
  </div>
  <div class:" field form-group">
    <%= form.label :user_Id %><br>
    <%= form.text_field :user_id, class:"form-control" ,value: current_user.id %>
  </div>
  <div class="field form-group">
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %> 

app/views/comments/show.html.erb
<p>
  <strong style="color:#58D68D">Title:</strong>
  <%= @comment.commenter %>
 </p>
 
 <p>
  <strong style="color:#58D68D">Body:</strong>
  <%= @comment.body %>
 </p>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_header.html.erb
 <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Aplication</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "EditProfile", edit_user_registration_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "logOut", destroy_user_session_path, data: { turbo_method: :delete,turbo_confirm: "do you want to logout"}, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "new comment", new_comment_path, class:"nav-link"%>
          </li>
        <% else %>
      
          <li class="nav-item">
           <%= link_to "Login", user_session_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "SignUp", new_user_registration_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "About", new_user_registration_path, class:"nav-link"%>
          </li>
      
        <% end %>
        
                  
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Demo App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render  'layouts/header'%>
    <div class="container">
       
      <% if notice %>
        <%= render 'layouts/alerts'%>
      <% end %>
    
      <br/>
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>